return {
  ["@Comment"] = { fg = "#8aa8fc" },
  ['@comment'] = { fg = "#8aa8fc" },
  ['Keyword'] = { fg = "#FFFF50" },
  ['@keyword'] = { fg = "#FFFF50" },
  ['@include'] = { fg = "#FFFF50" },
  ['@exception'] = { fg = "#FFFF50" },
  ['@conditional'] = { fg = "#FFFF50" },
  ['@string'] = { fg = "#d69f9f" },
  ['@number'] = { fg = "#e27477" },
  ['@function'] = { fg = "#71bf2e" },
  ['@function.call'] = { fg = "#71bf2e" },
  ['@variable'] = { fg = "#ce80f8" },
  ['@type'] = { fg = "#90ef3a" },
  ['@namespace'] = { fg = "#4ec9b0" },
  ['typescriptVariableDeclaration'] = { link = '@variable' },
  ['typescriptAliasDeclaration'] = { link = '@type' },
  ['typescriptTypeReference'] = { link = '@type' },
}
