return {
  -- this table overrides highlights in all themes
  Normal = { bg = "#000000" },
  ["@Comment"] = { fg = "#8aa8fc" },
  ['@comment'] = { fg = "#8aa8fc" },
  ['Keyword'] = { fg = "#FFFF50" },
  ['@keyword'] = { fg = "#FFFF50" },
  ['@include'] = { fg = "#FFFF50" },
  ['@exception'] = { fg = "#FFFF50" },
  ['@conditional'] = { fg = "#FFFF50" },
  ['@string'] = { fg = "#d69f9f" },
  ['@number'] = { fg = "#e27477" },
  ['@function'] = { fg = "#71bf2e" },
  ['@function.call'] = { fg = "#71bf2e" },
  ['@variable.builtin'] = { fg = "#ce80f8" },
  ['@variable'] = { fg = "#ce80f8" },
  ['@property'] = { fg = "#d4d4d4" },
  ['@type'] = { fg = "#90ef3a" },
  ['@tag'] = { fg = "#90ef3a" },
  ['@constructor.tsx'] = { fg = "#90ef3a" },
  ['@namespace'] = { fg = "#4ec9b0" },
  ['@parameter'] = { fg = '#d19a66'},
  ['typescriptVariableDeclaration'] = { link = '@variable' },
  ['typescriptAliasDeclaration'] = { link = '@type' },
  ['typescriptTypeReference'] = { link = '@type' },
  ['typescriptImport'] = { link = '@include' },
  ['@type.rust'] = { link = '@type'},
  ['@namespace.rust'] = { link = '@namespace'},
  ['@function.macro.rust'] = { fg = "#E4B8FB" },
  ['@property.toml'] = { link = 'Label'},
  ['@field'] = { link = 'Label'},
  ['NeoTreeGitUntracked'] = { fg = '#e5c06b'},
  ['NeoTreeGitModified'] = { fg = '#e5c06b'},
}
